apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
    name: web-nginx-ingress-service
    namespace: web
    annotations:
        kubernetes.io/ingress.class: nginx
        # nginx.ingress.kubernetes.io/ssl-passthrough: "true"
        # nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
        nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
    tls:
        - hosts:
              - sea.mengxin.ml
              - httpbin.mengxin.ml
              - mengxin.ml
              - www.mengxin.ml
              - mongo-express.mengxin.ml
              - chat.mengxin.ml
              - jupyter.mengxin.ml
              - prometheus.mengxin.ml
              - grafana.mengxin.ml
          secretName: mengxin-ml-cert
    rules:
        - host: sea.mengxin.ml
          http:
              paths:
                  - path: /
                    backend:
                        serviceName: sea-mengxin-ml-clusterip
                        servicePort: 80
        - host: www.mengxin.ml
          http:
              paths:
                  - path: /
                    backend:
                        serviceName: sea-mengxin-ml-clusterip
                        servicePort: 80
        - host: mengxin.ml
          http:
              paths:
                  - path: /
                    backend:
                        serviceName: sea-mengxin-ml-clusterip
                        servicePort: 80
        - host: httpbin.mengxin.ml
          http:
              paths:
                  - path: /
                    backend:
                        serviceName: httpbin-mengxin-ml-clusterip
                        servicePort: 80
        - host: mongo-express.mengxin.ml
          http:
              paths:
                  - path: /
                    backend:
                        serviceName: mongo-express-mengxin-ml-clusterip
                        servicePort: 8081
        - host: chat.mengxin.ml
          http:
              paths:
                  - path: /
                    backend:
                        serviceName: chat-mengxin-ml-clusterip
                        servicePort: 3000
        - host: jupyter.mengxin.ml
          http:
              paths:
                  - path: /
                    backend:
                        serviceName: jupyter-mengxin-ml-clusterip
                        servicePort: 8888
        - host: prometheus.mengxin.ml
          http:
              paths:
                  - path: /
                    backend:
                        serviceName: prometheus-mengxin-ml
                        servicePort: 9090
        - host: grafana.mengxin.ml
          http:
              paths:
                  - path: /
                    backend:
                        serviceName: grafana-mengxin-ml
                        servicePort: 80